const ATHIKARAMS = [
    // அறத்துப்பால் (Virtue) - 38 அதிகாரங்கள்
    { id: 1, ta: "கடவுள் வாழ்த்து", en: "The Praise of God", paal: 1, paalName: "அறத்துப்பால்", start: 1, end: 10   , si: "නමකර" },
    { id: 2, ta: "வான்சிறப்பு", en: "The Blessing of Rain", paal: 1, paalName: "அறத்துப்பால்", start: 11, end: 20   , si: "වැසි මහිම" },
    { id: 3, ta: "நீத்தார் பெருமை", en: "The Greatness of Ascetics", paal: 1, paalName: "அறத்துப்பால்", start: 21, end: 30   , si: "වීත රාගින්ගේ අගය" },
    { id: 4, ta: "அறன் வலியுறுத்தல்", en: "Assertion of the Strength of Virtue", paal: 1, paalName: "அறத்துப்பால்", start: 31, end: 40   , si: "දහම් හි බලය" },
    { id: 5, ta: "இல்வாழ்க்கை", en: "Domestic Life", paal: 1, paalName: "அறத்துப்பால்", start: 41, end: 50   , si: "ගිහි ජීවිතය" },
    { id: 6, ta: "வாழ்க்கைத் துணைநலம்", en: "The Worth of a Wife", paal: 1, paalName: "அறத்துப்பால்", start: 51, end: 60   , si: "සහකාරියගේ ගූණ" },
    { id: 7, ta: "மக்கட்பேறு", en: "The Wealth of Children", paal: 1, paalName: "அறத்துப்பால்", start: 61, end: 70   , si: "දරු සම්පත" },
    { id: 8, ta: "அன்புடைமை", en: "The Possession of Love", paal: 1, paalName: "அறத்துப்பால்", start: 71, end: 80   , si: "ආදරය" },
    { id: 9, ta: "விருந்தோம்பல்", en: "Hospitality", paal: 1, paalName: "அறத்துப்பால்", start: 81, end: 90   , si: "ආගන්තූක සත්කාරය" },
    { id: 10, ta: "இனியவை கூறல்", en: "The Utterance of Pleasant Words", paal: 1, paalName: "அறத்துப்பால்", start: 91, end: 100   , si: "ප්‍රිය වචන" },
    { id: 11, ta: "செய்ந்நன்றியறிதல்", en: "Gratitude", paal: 1, paalName: "அறத்துப்பால்", start: 101, end: 110   , si: "කළගූණ තැකීම" },
    { id: 12, ta: "நடுவு நிலைமை", en: "Impartiality", paal: 1, paalName: "அறத்துப்பால்", start: 111, end: 120   , si: "මැදහත් බව" },
    { id: 13, ta: "அடக்கம் உடைமை", en: "The Possession of Self-restraint", paal: 1, paalName: "அறத்துப்பால்", start: 121, end: 130   , si: "ආත්ම දමනය" },
    { id: 14, ta: "ஒழுக்கம் உடைமை", en: "The Possession of Decorum", paal: 1, paalName: "அறத்துப்பால்", start: 131, end: 140   , si: "මනා පැවැත්ම" },
    { id: 15, ta: "பிறனில் விழையாமை", en: "Not coveting another's Wife", paal: 1, paalName: "அறத்துப்பால்", start: 141, end: 150   , si: "පර" },
    { id: 16, ta: "பொறையுடைமை", en: "The Possession of Patience, Forbearance", paal: 1, paalName: "அறத்துப்பால்", start: 151, end: 160   , si: "ඉවසීම" },
    { id: 17, ta: "அழுக்காறாமை", en: "Not Envying", paal: 1, paalName: "அறத்துப்பால்", start: 161, end: 170   , si: "ඊර්ෂ්‍යා නො කිරීම" },
    { id: 18, ta: "வெஃகாமை", en: "Not Coveting", paal: 1, paalName: "அறத்துப்பால்", start: 171, end: 180   , si: "දළ ලොබින් වෙන්වීම" },
    { id: 19, ta: "புறங்கூறாமை", en: "Not Backbiting", paal: 1, paalName: "அறத்துப்பால்", start: 181, end: 190   , si: "කේලාම් නො කීම" },
    { id: 20, ta: "பயனில சொல்லாமை", en: "Against Vain Speaking", paal: 1, paalName: "அறத்துப்பால்", start: 191, end: 200   , si: "නිෂ්ඵල වචන නො කීම" },
    { id: 21, ta: "தீவினையச்சம்", en: "Dread of Evil Deeds", paal: 1, paalName: "அறத்துப்பால்", start: 201, end: 210   , si: "පවට බියවීම" },
    { id: 22, ta: "ஒப்புரவறிதல்", en: "Duty to Society", paal: 1, paalName: "அறத்துப்பால்", start: 211, end: 220   , si: "පරෝපකාරය" },
    { id: 23, ta: "ஈகை", en: "Giving", paal: 1, paalName: "அறத்துப்பால்", start: 221, end: 230   , si: "දානය" },
    { id: 24, ta: "புகழ்", en: "Renown", paal: 1, paalName: "அறத்துப்பால்", start: 231, end: 240   , si: "යසස" },
    { id: 25, ta: "அருளுடைமை", en: "Compassion", paal: 1, paalName: "அறத்துப்பால்", start: 241, end: 250   , si: "කරුණාව" },
    { id: 26, ta: "புலால் மறுத்தல்", en: "Abstinence from Flesh", paal: 1, paalName: "அறத்துப்பால்", start: 251, end: 260   , si: "මස් කෑමෙන් වැළකීම" },
    { id: 27, ta: "தவம்", en: "Penance", paal: 1, paalName: "அறத்துப்பால்", start: 261, end: 270   , si: "තපස" },
    { id: 28, ta: "கூடா ஒழுக்கம்", en: "Imposture", paal: 1, paalName: "அறத்துப்பால்", start: 271, end: 280   , si: "නො මනා පැවැත්ම" },
    { id: 29, ta: "கள்ளாமை", en: "The Absence of Fraud", paal: 1, paalName: "அறத்துப்பால்", start: 281, end: 290   , si: "සොරකම් නො කිරීම" },
    { id: 30, ta: "வாய்மை", en: "Veracity", paal: 1, paalName: "அறத்துப்பால்", start: 291, end: 300   , si: "සබවස" },
    { id: 31, ta: "வெகுளாமை", en: "Restraining Anger", paal: 1, paalName: "அறத்துப்பால்", start: 301, end: 310   , si: "නො කිපීම" },
    { id: 32, ta: "இன்னா செய்யாமை", en: "Not doing Evil", paal: 1, paalName: "அறத்துப்பால்", start: 311, end: 320   , si: "අවිහිංසාව" },
    { id: 33, ta: "கொல்லாமை", en: "Not killing", paal: 1, paalName: "அறத்துப்பால்", start: 321, end: 330   , si: "නො මැරීම" },
    { id: 34, ta: "நிலையாமை", en: "Instability", paal: 1, paalName: "அறத்துப்பால்", start: 331, end: 340   , si: "අනිත්‍යය" },
    { id: 35, ta: "துறவு", en: "Renunciation", paal: 1, paalName: "அறத்துப்பால்", start: 341, end: 350   , si: "ගිහිගෙය හැර යාම" },
    { id: 36, ta: "மெய்யுணர்தல்", en: "Truth-Consciousness", paal: 1, paalName: "அறத்துப்பால்", start: 351, end: 360   , si: "නි වැරදි දැකීම" },
    { id: 37, ta: "அவா அறுத்தல்", en: "Curbing of Desire", paal: 1, paalName: "அறத்துப்பால்", start: 361, end: 370   , si: "තණ්හාව දුරු කිරීම" },
    { id: 38, ta: "ஊழ்", en: "Fate", paal: 1, paalName: "அறத்துப்பால்", start: 371, end: 380   , si: "කර්මය" },

    // பொருட்பால் (Wealth) - 70 அதிகாரங்கள்
    { id: 39, ta: "இறைமாட்சி", en: "The Greatness of a King", paal: 2, paalName: "பொருட்பால்", start: 381, end: 390   , si: "රාජ මහිමය" },
    { id: 40, ta: "கல்வி", en: "Learning", paal: 2, paalName: "பொருட்பால்", start: 391, end: 400   , si: "උගත්කම" },
    { id: 41, ta: "கல்லாமை", en: "Ignorance", paal: 2, paalName: "பொருட்பால்", start: 401, end: 410   , si: "නුගත්කම" },
    { id: 42, ta: "கேள்வி", en: "Hearing", paal: 2, paalName: "பொருட்பால்", start: 411, end: 420   , si: "බහු ශ්‍රුත බව" },
    { id: 43, ta: "அறிவுடைமை", en: "The Possession of Knowledge", paal: 2, paalName: "பொருட்பால்", start: 421, end: 430   , si: "නැණැති බව" },
    { id: 44, ta: "குற்றங்கடிதல்", en: "The Correction of Faults", paal: 2, paalName: "பொருட்பால்", start: 431, end: 440   , si: "දොස් නැති කිරීම" },
    { id: 45, ta: "பெரியாரைத் துணைக்கோடல்", en: "Seeking the Aid of Great Men", paal: 2, paalName: "பொருட்பால்", start: 441, end: 450   , si: "මහතූන්ගෙන් උදව් ගැනීම" },
    { id: 46, ta: "சிற்றினம் சேராமை", en: "Avoiding mean Associations", paal: 2, paalName: "பொருட்பால்", start: 451, end: 460   , si: "පාප මිත්‍රයන් සෙවනය නො කිරීම" },
    { id: 47, ta: "தெரிந்து செயல்வகை", en: "Acting after due Consideration", paal: 2, paalName: "பொருட்பால்", start: 461, end: 470   , si: "විමසා ක්‍රියා කිරීම" },
    { id: 48, ta: "வலியறிதல்", en: "The Knowledge of Power", paal: 2, paalName: "பொருட்பால்", start: 471, end: 480   , si: "බලය දැන ගැනිම" },
    { id: 49, ta: "காலமறிதல்", en: "Knowing the fitting Time", paal: 2, paalName: "பொருட்பால்", start: 481, end: 490   , si: "කාලය දැන ගැනීම" },
    { id: 50, ta: "இடனறிதல்", en: "Knowing the Place", paal: 2, paalName: "பொருட்பால்", start: 491, end: 500   , si: "ස්ථානය දැන ගැනීම" },
    { id: 51, ta: "தெரிந்து தெளிதல்", en: "Selection and Confidence", paal: 2, paalName: "பொருட்பால்", start: 501, end: 510   , si: "විමසා තීරණය කිරීම" },
    { id: 52, ta: "தெரிந்து வினையாடல்", en: "Selection and Employment", paal: 2, paalName: "பொருட்பால்", start: 511, end: 520   , si: "විමසා පැවරීම" },
    { id: 53, ta: "சுற்றந் தழால்", en: "Cherishing Kinsmen", paal: 2, paalName: "பொருட்பால்", start: 521, end: 530   , si: "සබැඳියාව" },
    { id: 54, ta: "பொச்சாவாமை", en: "Unforgetfulness", paal: 2, paalName: "பொருட்பால்", start: 531, end: 540   , si: "අමතක නො කිරීම" },
    { id: 55, ta: "செங்கோன்மை", en: "The Right Sceptre", paal: 2, paalName: "பொருட்பால்", start: 541, end: 550   , si: "සෘජු පාලනය" },
    { id: 56, ta: "கொடுங்கோன்மை", en: "The Cruel Sceptre", paal: 2, paalName: "பொருட்பால்", start: 551, end: 560   , si: "නපුරු පාලනය" },
    { id: 57, ta: "வெருவந்த செய்யாமை", en: "Absence of Terrorism", paal: 2, paalName: "பொருட்பால்", start: 561, end: 570   , si: "භය ජනක දේ නො කිරීම" },
    { id: 58, ta: "கண்ணோட்டம்", en: "Benignity", paal: 2, paalName: "பொருட்பால்", start: 571, end: 580   , si: "කරුණාව" },
    { id: 59, ta: "ஒற்றாடல்", en: "Detectives", paal: 2, paalName: "பொருட்பால்", start: 581, end: 590   , si: "චර පුරුෂ සේවය" },
    { id: 60, ta: "ஊக்கம் உடைமை", en: "Energy", paal: 2, paalName: "பொருட்பால்", start: 591, end: 600   , si: "දිරිය" },
    { id: 61, ta: "மடி இன்மை", en: "Unsluggishness", paal: 2, paalName: "பொருட்பால்", start: 601, end: 610   , si: "අලස නො වීම" },
    { id: 62, ta: "ஆள்வினை உடைமை", en: "Manly Effort", paal: 2, paalName: "பொருட்பால்", start: 611, end: 620   , si: "ක්‍රියා සුර බව" },
    { id: 63, ta: "இடுக்கண் அழியாமை", en: "Hopefulness in Trouble", paal: 2, paalName: "பொருட்பால்", start: 621, end: 630   , si: "අත් නො හැර ක්‍රියා කිරිම" },
    { id: 64, ta: "அமைச்சு", en: "The Office of Minister of state", paal: 2, paalName: "பொருட்பால்", start: 631, end: 640   , si: "ඇමතිවරු" },
    { id: 65, ta: "சொல்வன்மை", en: "Power of Speech", paal: 2, paalName: "பொருட்பால்", start: 641, end: 650   , si: "කථිකත්වය" },
    { id: 66, ta: "வினைத் தூய்மை", en: "Purity in Action", paal: 2, paalName: "பொருட்பால்", start: 651, end: 660   , si: "ක්‍රියාවෙහි පිරිසිදු බව" },
    { id: 67, ta: "வினைத்திட்பம்", en: "Power in Action", paal: 2, paalName: "பொருட்பால்", start: 661, end: 670   , si: "ක්‍රියාවෙහි ස්ථිර බව" },
    { id: 68, ta: "வினை செயல்வகை", en: "Modes of Action", paal: 2, paalName: "பொருட்பால்", start: 671, end: 680   , si: "ක්‍රියා කරන විදිය" },
    { id: 69, ta: "தூது", en: "The Envoy", paal: 2, paalName: "பொருட்பால்", start: 681, end: 690   , si: "රාජ දූතයා" },
    { id: 70, ta: "மன்னரைச் சேர்ந்து ஒழுகல்", en: "Conduct in the Presence of the King", paal: 2, paalName: "பொருட்பால்", start: 691, end: 700   , si: "රජුන් ආශ්‍රය" },
    { id: 71, ta: "குறிப்பறிதல்", en: "The Knowledge of Indications", paal: 2, paalName: "பொருட்பால்", start: 701, end: 710   , si: "සලකූණෙන් දැන ගැනීම" },
    { id: 72, ta: "அவை அறிதல்", en: "The Knowledge of the Council Chamber", paal: 2, paalName: "பொருட்பால்", start: 711, end: 720   , si: "සභාව දැන ගැනීම" },
    { id: 73, ta: "அவை அஞ்சாமை", en: "Not to dread the Council", paal: 2, paalName: "பொருட்பால்", start: 721, end: 730   , si: "සභා භය නැති බව" },
    { id: 74, ta: "நாடு", en: "The Land", paal: 2, paalName: "பொருட்பால்", start: 731, end: 740   , si: "රට" },
    { id: 75, ta: "அரண்", en: "The Fortification", paal: 2, paalName: "பொருட்பால்", start: 741, end: 750   , si: "බළ කොටුව" },
    { id: 76, ta: "பொருள் செயல்வகை", en: "Way of Accumulating Wealth", paal: 2, paalName: "பொருட்பால்", start: 751, end: 760   , si: "ධන ඉපයීම" },
    { id: 77, ta: "படை மாட்சி", en: "The Excellence of an Army", paal: 2, paalName: "பொருட்பால்", start: 761, end: 770   , si: "යුද හමුදා මහිම" },
    { id: 78, ta: "படைச் செருக்கு", en: "Military Spirit", paal: 2, paalName: "பொருட்பால்", start: 771, end: 780   , si: "හමුදා වීරත්වය" },
    { id: 79, ta: "நட்பு", en: "Friendship", paal: 2, paalName: "பொருட்பால்", start: 781, end: 790   , si: "ස්නේහය" },
    { id: 80, ta: "நட்பாராய்தல்", en: "Investigation in forming Friendships", paal: 2, paalName: "பொருட்பால்", start: 791, end: 800   , si: "ස්නේහය පිරික්සීම" },
    { id: 81, ta: "பழைமை", en: "Familiarity", paal: 2, paalName: "பொருட்பால்", start: 801, end: 810   , si: "ඉපැරණි සෙනෙහස" },
    { id: 82, ta: "தீ நட்பு", en: "Evil Friendship", paal: 2, paalName: "பொருட்பால்", start: 811, end: 820   , si: "නපුරු සෙනෙහස" },
    { id: 83, ta: "கூடா நட்பு", en: "Unreal Friendship", paal: 2, paalName: "பொருட்பால்", start: 821, end: 830   , si: "ව්‍යාජ සෙනෙහස" },
    { id: 84, ta: "பேதைமை", en: "Folly", paal: 2, paalName: "பொருட்பால்", start: 831, end: 840   , si: "මෝඩකම" },
    { id: 85, ta: "புல்லறிவாண்மை", en: "Ignorance", paal: 2, paalName: "பொருட்பால்", start: 841, end: 850   , si: "මඳ දැනුම" },
    { id: 86, ta: "இகல்", en: "Hostility", paal: 2, paalName: "பொருட்பால்", start: 851, end: 860   , si: "විරුද්ධකම" },
    { id: 87, ta: "பகை மாட்சி", en: "The Might of Hatred", paal: 2, paalName: "பொருட்பால்", start: 861, end: 870   , si: "සතූරුකමේ අගය" },
    { id: 88, ta: "பகைத்திறம் தெரிதல்", en: "Knowing the Quality of Hate", paal: 2, paalName: "பொருட்பால்", start: 871, end: 880   , si: "සතූරු බල දැන ගැනීම" },
    { id: 89, ta: "உட்பகை", en: "Enmity within", paal: 2, paalName: "பொருட்பால்", start: 881, end: 890   , si: "ඇතූළත සතූරුකම" },
    { id: 90, ta: "பெரியாரைப் பிழையாமை", en: "Not Offending the Great", paal: 2, paalName: "பொருட்பால்", start: 891, end: 900   , si: "මහතූන්ට අවමන් නොකිරිම" },
    { id: 91, ta: "பெண்வழிச் சேறல்", en: "Being led by Women", paal: 2, paalName: "பொருட்பால்", start: 901, end: 910   , si: "බිරියට යටත්වීම" },
    { id: 92, ta: "வரைவின் மகளிர்", en: "Wanton Women", paal: 2, paalName: "பொருட்பால்", start: 911, end: 920   , si: "පොදු ස්ත්‍රීය" },
    { id: 93, ta: "கள்ளுண்ணாமை", en: "Not Drinking Palm-Wine", paal: 2, paalName: "பொருட்பால்", start: 921, end: 930   , si: "සුරා පානය නොකිරීම" },
    { id: 94, ta: "சூது", en: "Gambling", paal: 2, paalName: "பொருட்பால்", start: 931, end: 940   , si: "සූදුව" },
    { id: 95, ta: "மருந்து", en: "Medicine", paal: 2, paalName: "பொருட்பால்", start: 941, end: 950   , si: "පිළියම්" },
    { id: 96, ta: "குடிமை", en: "Nobility", paal: 2, paalName: "பொருட்பால்", start: 951, end: 960   , si: "උසස් කූලයෙහි ඉපදීම" },
    { id: 97, ta: "மானம்", en: "Honour", paal: 2, paalName: "பொருட்பால்", start: 961, end: 970   , si: "ආත්ම ගෞරවය99" },
    { id: 98, ta: "பெருமை", en: "Greatness", paal: 2, paalName: "பொருட்பால்", start: 971, end: 980   , si: "උතූම්බව" },
    { id: 99, ta: "சான்றாண்மை", en: "Perfectness", paal: 2, paalName: "பொருட்பால்", start: 981, end: 990   , si: "සාධුත්වය" },
    { id: 100, ta: "பண்புடைமை", en: "Courtesy", paal: 2, paalName: "பொருட்பால்", start: 991, end: 1000   , si: "ශීලාචාර බව" },
    { id: 101, ta: "நன்றியில் செல்வம்", en: "Wealth without Benefaction", paal: 2, paalName: "பொருட்பால்", start: 1001, end: 1010   , si: "හොඳ පල නොදෙන වස්තූව" },
    { id: 102, ta: "நாணுடைமை", en: "Shame", paal: 2, paalName: "பொருட்பால்", start: 1011, end: 1020   , si: "ලැජ්ජාව (හිරිය)" },
    { id: 103, ta: "குடிசெயல் வகை", en: "The Way of Maintaining the Family", paal: 2, paalName: "பொருட்பால்", start: 1021, end: 1030   , si: "පවුල් රකින විදිය" },
    { id: 104, ta: "உழவு", en: "Farming", paal: 2, paalName: "பொருட்பால்", start: 1031, end: 1040   , si: "ගොවිතැන" },
    { id: 105, ta: "நல்குரவு", en: "Poverty", paal: 2, paalName: "பொருட்பால்", start: 1041, end: 1050   , si: "දුගී බව" },
    { id: 106, ta: "இரவு", en: "Mendicancy", paal: 2, paalName: "பொருட்பால்", start: 1051, end: 1060   , si: "හිඟමන" },
    { id: 107, ta: "இரவச்சம்", en: "The Dread of Mendicancy", paal: 2, paalName: "பொருட்பால்", start: 1061, end: 1070   , si: "හිඟමනට බිය" },
    { id: 108, ta: "கயமை", en: "Baseness", paal: 2, paalName: "பொருட்பால்", start: 1071, end: 1080   , si: "අධමතාවය" },

    // காமத்துப்பால் (Love) - 25 அதிகாரங்கள்
    { id: 109, ta: "தகை அணங்குறுத்தல்", en: "The Pre-marital love", paal: 3, paalName: "காமத்துப்பால்", start: 1081, end: 1090   , si: "රුපය දැක මත්වීම" },
    { id: 110, ta: "குறிப்பறிதல்", en: "Recognition of the Signs", paal: 3, paalName: "காமத்துப்பால்", start: 1091, end: 1100   , si: "සලකූණින් දැනීම" },
    { id: 111, ta: "புணர்ச்சி மகிழ்தல்", en: "Rejoicing in the Embrace", paal: 3, paalName: "காமத்துப்பால்", start: 1101, end: 1110   , si: "අභිරමණයෙහි ප්‍රීතීය" },
    { id: 112, ta: "நலம் புனைந்து உரைத்தல்", en: "The Praise of her Beauty", paal: 3, paalName: "காமத்துப்பால்", start: 1111, end: 1120   , si: "රස වැණුම්" },
    { id: 113, ta: "காதற் சிறப்புரைத்தல்", en: "Declaration of Love's special Excellence", paal: 3, paalName: "காமத்துப்பால்", start: 1121, end: 1130   , si: "ප්‍රේමය ප්‍රකාශ කිරීම" },
    { id: 114, ta: "நாணுத் துறவுரைத்தல்", en: "The Abandonment of Reserve", paal: 3, paalName: "காமத்துப்பால்", start: 1131, end: 1140   , si: "ලැජ්ජාව අත් හැරීම" },
    { id: 115, ta: "அலர் அறிவுறுத்தல்", en: "The Announcement of the Rumour", paal: 3, paalName: "காமத்துப்பால்", start: 1141, end: 1150   , si: "කට කතා" },
    { id: 116, ta: "பிரிவு ஆற்றாமை", en: "Separation unendurable", paal: 3, paalName: "காமத்துப்பால்", start: 1151, end: 1160   , si: "දැරිය නොහැකි වියෝව" },
    { id: 117, ta: "படர்மெலிந் திரங்கல்", en: "Complainings", paal: 3, paalName: "காமத்துப்பால்", start: 1161, end: 1170   , si: "දුකින් මැලවීම" },
    { id: 118, ta: "கண் விதுப்பழிதல்", en: "Eyes consumed with Grief", paal: 3, paalName: "காமத்துப்பால்", start: 1171, end: 1180   , si: "නුවන් මැලවීම" },
    { id: 119, ta: "பசப்புறு பருவரல்", en: "The Pallid Hue", paal: 3, paalName: "காமத்துப்பால்", start: 1181, end: 1190   , si: "දුර්වර්ණවීම" },
    { id: 120, ta: "தனிப்படர் மிகுதி", en: "The Solitary Anguish", paal: 3, paalName: "காமத்துப்பால்", start: 1191, end: 1200   , si: "තනිවීමේ දුක" },
    { id: 121, ta: "நினைந்தவர் புலம்பல்", en: "Sad Memories", paal: 3, paalName: "காமத்துப்பால்", start: 1201, end: 1210   , si: "සිතා ශෝකවීම" },
    { id: 122, ta: "கனவுநிலை உரைத்தல்", en: "The Visions of the Night", paal: 3, paalName: "காமத்துப்பால்", start: 1211, end: 1220   , si: "සිහින කීම" },
    { id: 123, ta: "பொழுதுகண்டு இரங்கல்", en: "Lamentations at Eventide", paal: 3, paalName: "காமத்துப்பால்", start: 1221, end: 1230   , si: "සන්ධ්‍යාගමනය දැක විරහ …" },
    { id: 124, ta: "உறுப்புநலன் அழிதல்", en: "Wasting Away", paal: 3, paalName: "காமத்துப்பால்", start: 1231, end: 1240   , si: "ශරිර ශෝභාව අඩුවීම" },
    { id: 125, ta: "நெஞ்சொடு கிளத்தல்", en: "Soliloquy", paal: 3, paalName: "காமத்துப்பால்", start: 1241, end: 1250   , si: "හිතට ඔවාදීම" },
    { id: 126, ta: "நிறையழிதல்", en: "Reserve Overcome", paal: 3, paalName: "காமத்துப்பால்", start: 1251, end: 1260   , si: "සීමාව ඉක්මවා යාම" },
    { id: 127, ta: "அவர்வயின் விதும்பல்", en: "Mutual Desire", paal: 3, paalName: "காமத்துப்பால்", start: 1261, end: 1270   , si: "ඔහුගේ ඊමට කැමති වීම" },
    { id: 128, ta: "குறிப்பறிவுறுத்தல்", en: "The Reading of the Signs", paal: 3, paalName: "காமத்துப்பால்", start: 1271, end: 1280   , si: "සලකූණින් ඇඟවුම" },
    { id: 129, ta: "புணர்ச்சி விதும்பல்", en: "Desire for Reunion", paal: 3, paalName: "காமத்துப்பால்", start: 1281, end: 1290   , si: "අභිරමණය පිනිස යුහුසුලු වීම" },
    { id: 130, ta: "நெஞ்சொடு புலத்தல்", en: "Expostulation with Oneself", paal: 3, paalName: "காமத்துப்பால்", start: 1291, end: 1300   , si: "සිත සමග කලකිරීම" },
    { id: 131, ta: "புலவி", en: "Pouting", paal: 3, paalName: "காமத்துப்பால்", start: 1301, end: 1310   , si: "ව්‍යාජ කලකිරුම" },
    { id: 132, ta: "புலவி நுணுக்கம்", en: "Feigned Anger", paal: 3, paalName: "காமத்துப்பால்", start: 1311, end: 1320   , si: "ව්‍යාජ කලකිරුමෙහි සියුම් බව" },
    { id: 133, ta: "ஊடலுவகை", en: "The Pleasures of Temporary Variance", paal: 3, paalName: "காமத்துப்பால்", start: 1321, end: 1330   , si: "ව්‍යාජ කලකිරිමෙන් පසු ………" }
];
